(setq inhibit-startup-screen t)
(menu-bar-mode 0)
(tool-bar-mode 0)
(ido-mode 1)
(ido-everywhere 1)
(setq ido-show-dot-for-dired t)
(set-frame-font "Ubuntu Mono 18" nil t)
(scroll-bar-mode 0)
(column-number-mode 1)
(show-paren-mode 1)

(setq tramp-auto-save-directory "/tmp")
(setq make-backup-files nil)

(setq display-line-numbers-type 'relative) 
(global-display-line-numbers-mode)

(setq-default indent-tabs-mode nil)
(setq-default tab-width 4)
(setq c-set-style "k&r")
(setq c-basic-offset 4)
